name: ml
channels:
  - conda-forge
  - defaults
dependencies:
#   - cudatoolkit=10.2
#   - cudnn=7.6.5=cuda10.2_0
  - pip=20.2.4
  # - pydicom=1.3.0=py_0
  - python=3.6
  - pip:
    - numpy==1.16.4
    # - opencv-contrib-python==4.1.0.25
    # - pillow==6.1.0
    # - tensorflow-gpu==2.0.0b1
    # - wrapt==1.11.2

