name: ml
channels:
  - defaults
  - pytorch
dependencies:
#   - cudatoolkit=10.2
#   - cudnn=7.6.5=cuda10.2_0
  - python=3.7
  - pip
  - pytorch=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=10.2
  - matplotlib
#   - tensorflow
  - pillow=6.1
  - tqdm
  - imageio
  - pip:
    - terminaltables
    - opencv-contrib-python
    - easydict
    - albumentations
    - pydicom==1.3.0
    - pandas
    - torchsummary # 1.5.1
#prefix: /data.local/tuannm/Git-Code/image-segmentation/env
    


